services:
  api:
    build:
      context: ..
      dockerfile: docker/DockerFile
    container_name: backend_api
    ports:
      - "8000:8080"
    depends_on:
      - sqlserver
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskDb;User=sa;Password=OristoSQLPassword@123;TrustServerCertificate=True

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OristoSQLPassword@123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

